// Mocks generated by Mockito 5.3.2 from annotations
// in transisi/test/features/authentication/data/datasource/authentication_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:transisi/src/features/authentication/data/datasource/authentication_datasource.dart'
    as _i3;
import 'package:transisi/src/features/authentication/data/model/authentication_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationModel_0 extends _i1.SmartFake
    implements _i2.AuthenticationModel {
  _FakeAuthenticationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationDatasource extends _i1.Mock
    implements _i3.AuthenticationDatasource {
  @override
  _i4.Future<_i2.AuthenticationModel> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.AuthenticationModel>.value(
            _FakeAuthenticationModel_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.AuthenticationModel>.value(
            _FakeAuthenticationModel_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthenticationModel>);
  @override
  _i4.Future<String?> loginFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #loginFromStorage,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}
